"""Added QR Layer Modifications

Revision ID: 8ac2f60a9ff4
Revises: b605754a8831
Create Date: 2026-02-04 00:25:54.214430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac2f60a9ff4'
down_revision = 'b605754a8831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projector_tokens',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    
    checkin_enum = sa.Enum('ble', 'qr', 'manual', name='checkinenum')
    try:
        checkin_enum.create(op.get_bind())
    except Exception:
        pass
    
    with op.batch_alter_table('attendance_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_id', sa.String(length=255), nullable=True))
        batch_op.add_column(
            sa.Column(
                'checkin_method', 
                checkin_enum, 
                nullable=False, 
                server_default='ble'
            )
        )
        batch_op.create_unique_constraint('_unique_device_per_session', ['session_id', 'device_id'])

    with op.batch_alter_table('faculties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_secret_key', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('qr_secret_key')

    with op.batch_alter_table('faculties', schema=None) as batch_op:
        batch_op.drop_column('latitude')
        batch_op.drop_column('longitude')

    with op.batch_alter_table('attendance_logs', schema=None) as batch_op:
        batch_op.drop_constraint('_unique_device_per_session', type_='unique')
        batch_op.drop_column('checkin_method')
        batch_op.drop_column('device_id')

    checkin_enum = sa.Enum('ble', 'qr', 'manual', name='checkinenum')
    checkin_enum.drop(op.get_bind())
    
    op.drop_table('projector_tokens')
    # ### end Alembic commands ###
