"""Added 3 tables: Session, Attendance, Faculties

Revision ID: b605754a8831
Revises: cd6a9a352065
Create Date: 2025-12-04 00:20:42.758140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b605754a8831'
down_revision = 'cd6a9a352065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faculty_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'faculties', ['faculty_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faculty_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'faculties', ['faculty_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('faculty_id')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('faculty_id')

    op.drop_table('faculties')
    # ### end Alembic commands ###
